language: r
r:
  - release
dist: precise # apparmor is disabled in trusty
sudo: required
cache: false
warnings_are_errors: false
r_packages:
  - roxygen2
  - devtools
  - testthat
  - Rcpp
  - covr
  - RAppArmor
r_github_packages:
  - Displayr/redisMonitor
  - Microsoft/AzureSMR
  - Displayr/opencpu

before_install:
  - sudo rm /etc/apt/sources.list.d/mongodb*.list*
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo sh -c 'echo "deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse" >> /etc/apt/sources.list'
  - sudo sh -c 'echo "deb-src http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse" >> /etc/apt/sources.list'
  - sudo apt-get update
  - sudo apt-get purge gcc
  - sudo apt-get install gcc-5 g++-5 && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - sudo apt-get install -y libev-dev redis-tools redis-server librsvg2-dev libprotobuf-dev libprotoc-dev subversion
  - sudo apt-get build-dep "libapparmor-dev=2.8.95~2430-0ubuntu5" -qq
  - sudo apt-get -b source -t trusty "libapparmor-dev=2.8.95~2430-0ubuntu5" -qq
  - git clone https://github.com/redis/hiredis && make -C hiredis && sudo make -C hiredis install
  - sudo ldconfig
  - sudo ls -R /etc/apparmor.d
script:
  - git clone "https://$GITHUB_PAT@github.com/Displayr/opencpu.git"
  - cd opencpu && git checkout matt && R -e 'devtools::test()'
